export const handleError = (error, req, res, next) => console.log('error:', error.message);
